version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/url_shortener_db
    ports:
      - "5001:5001"

  url_shortener_service:
    build:
      context: ./url_shortener
      dockerfile: Dockerfile
    container_name: url_shortener_service
    depends_on:
      - db
      - auth_service
    environment:
      - DATABASE_URL=postgresql://user:password@db/url_shortener_db
      - AUTH_SERVICE_URL=http://auth_service:5001
    ports:
      - "5000:5000"

volumes:
  db_data:
