version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d url_shortener_db"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db/url_shortener_db
    ports:
      - "5001:5001"

  url_shortener_service:
    build:
      context: ./url_shortener
      dockerfile: Dockerfile
    container_name: url_shortener_service
    depends_on:
      - auth_service
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db/url_shortener_db
      - AUTH_SERVICE_URL=http://auth_service:5001
    ports:
      - "5000:5000"

volumes:
  db_data:
