events {}

http {
    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://145.100.130.89:5001/;
        }

        location /api/shorten/ {
            proxy_pass http://145.100.130.89:5000/;
        }
    }
}
